language: go
go:
    - 1.x
    - "1.8"
    - "1.9"
    - 1.10.x
script:
    - go test -v ./...
    - go test -race -coverprofile=coverage.txt -covermode=atomic
dd:
    secure: uDpTQGf6tzkVsG+MqikhLcUf6wxOpnXvgn058rlls5qeWz0NvmHxnZS9OVmqoRDIOzf6ycnFd1eSSPw2CkSKVwiMcEW8W8s97n4Yk92bXdtWV+Qwutym0XtyaOP0C7lB04KfMB1FQT7YoKTRTsUxR+V9oNafMzr0pv0tcuMOKXPpVvYtLl7JWGCiCATk9cS6nzO0fSdgFREKtTuFGKuYGyWAOpnIE1JwFT15Nl2PujtYvGjKFG7BbB8Qky7a/tGdUozb+7SYoTb6FUscse8mqmXodNF8v2yoFaY8FC1QVIJV2e5A5S+nINU43dPh60P3/Fvmui/TDpE2HXlctVzpZztn8354H3HNOOzDGdkq44uCEYvdelscHMHSyHy7XqcN9fM+I8fmiXi1kaBVzZk5KjfJFhQr5QcIGUffmBt6enDhbo2WXPX7Sw+WrctoUVRkYhujKmEFwqb8KAjvZvehx3PFrDQsabAaz/WZ2Dq0niQ+Xq8lxW2B6MnHxMj3BnZE82zciGTpuIIHRi0OSIfKIPSmeT7YSAq+/6mOJrl3drewLhM1jp+eYWzaXdWaFW6hDyVWoDY9vJB9zoI0H2D/Lgd93BOIePxOkzE0ns+2D9pPt7TOkQTx8qLk+SmaMvbyPk+uAzpNoqUNbry2A6b9TzuqNcm1iME1y8hAxE7if1g=
after_success:
    - bash <(curl -s https://codecov.io/bash)
 