language: go
go:
    - 1.x
    - "1.8"
    - "1.9"
    - 1.10.x
script:
    - go test -v ./...
    - go test -race -coverprofile=coverage.txt -covermode=atomic
dd:
    secure: Z4zXccGuJVwR28CjJNH3v6cOJeKlt/fV8gzw68dElCi+BZN9Rc5klvyaUciIskSh1vGpFrzsUmN9314pOWXuotq8J97iwmFRh3IpnCCp5uJP8a3FC7O4VUrxZV085itMgQw8Zpcn+EANZRmgMRidxgzPeCrHmpZ+4zmZXZ40C9v3D+G+4/XN/+VGFL1BbuvztZelHwP+2AoxJL7z0KzN1FbyKXMiRJWhDDBdFvvnYT78IdPitRGgAOENHfLQQzFiGPa4tQYOOyKg0jLvTDGHsCfNWcKlNr5pfhBD7p6TWCzZWVg64cepO0wEbgW17OV+3RDnstZkSMd3EV+oL+r5wpGBlOoQdCYX5/vdn5TpqNtFGtK1X+rUXJeFmyAotPNVb5Pj4W5QPuUJ1KOhUUU6TiP1GRAY7Lb9Ww7VzF7avdNtbXSZfwZHjBdCWfV/9+BzTjZrkFqi3TlNSuwKsAapj5ShD82PjYIBvwNCZmRxZiJON20AY/jS4eBoluOrqqj5Ru0gGFzJ2wNs7kJNgClP3kH76Q3BWPmy3GPwLJLQ38GL1SGQOQAbspI0yuRimrH7VHnJN0Lu7JxsDzhFcfuMug0AFMJjNpmWR7HoSwMaXHqGUM3EUh8/x/Cn0/qzJKRb1qSRkQtJ073waWcwp3YDIMcsyTz6TD9yKAGMThgLBh0=
after_success:
    - bash <(curl -s https://codecov.io/bash)
 