language: go
go:
    - 1.x
    - "1.8"
    - "1.9"
    - 1.10.x
script:
    - go test -v ./...
    - go test -race -coverprofile=coverage.txt -covermode=atomic
dd:
    secure: DcmAE2VtR/ohuIAcG/F1gLt0/C3h0LlP+pHfc6rVNxUAJAxCv1ZmzSKlfml6wXfwqsOynb6mCREb6mN3tX7zEx9k5vfDmXdXVMJP9lL9kAu9Z0lGszIGqlDSfZ5J5ZWy+qZ78nmRTZtrhkB6XJsA9CpnHJfPBxbD9NnTWnSS5lGIojO9u8VBPV1C3q4wucAqQMFySQjyHclfj+M5RxTNkxM5zAQwiAzy1J0tTzfM5sdKSE5nhixm+cXvnrITvPfB1DovtfF5Xt9e8LvRPaKAhYvJZfbAj4v9DGp10edm8sAg5L/LmKW2hZMc6z87KTNbPRcvcScaAJZCnlkfxROaCz9Bzu9nxygBxUFtK04KLZNwgGy7okIix4HW2BV5nAgwGOkDxHdJgA0Niek1HVCc68IodN/ZAyEQJFPsSNsISsJnFt78htlbRhy7rrj2R0rfpEumCBW+f3edSaHRjzigUpIQtQ8bmiQB4AheMLTOXIWY6Osjl98AeKlyxpM1tb4XpeikKOzdh+C9TFSsp+nAsyN4vkvUbYz39t9ho7/beRs91Fs+QWKYVZV65aaW7/YQx55wHGhC3U7nXoVZKLguXyK8gajnqcB0m4oXfs+Z4bfVPk/FCIdXniSrKi1YNZZ1ofIhghJz6S9YW4qgAJfVmwo4zerc/U0hBsD/9I/VbYI=
after_success:
    - bash <(curl -s https://codecov.io/bash)
 