language: go
go:
- 1.x
- '1.8'
- '1.9'
- 1.10.x

install:
  - go get github.com/mattn/goveralls


script:
- go test -v ./...
- go test -race -coverprofile=coverage.txt -covermode=atomic
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
dd:
  secure: srjkLJXcw86FP7NeM+nZnqbkwlJI2jXGreufnzDQgNCt1tVO6wOzijAl9jpmrw+5ygIRsdAWwx84MVd/fyojwmIWNfqfsAO0ylbEQB+GVm8vpyn3xabP0sVib+zY1KLxBbu64j70bZxQfhnNGZ0G93riz9coHs0am7/BCXZJ6psa2ndDIOyJXZMEP10Ko8wCsHI2Npe7hZYeF7g2Ikdhoo2YU+4d/wZLmxTaZ/64A0ewbyVFVEZW5f0NTvWM9K3KKHTVZ0+nYPcQ7xExXzUl6HKK8PHIj/n4bPlzUDS70xXMNNxCfYITS+jlohhUwmPrphWbFIVxyoFZPvAjBpKkS4jvPAAWw4VhS+3VQo9kJ1GQ1ovvwDZ/WNYZD6eFG4527TBa9LeOmq80gqSbqkJibccF7tJwkOu0Df9pQWoM5huMiqRh0owN6CJXX/CJ0FvLZaqJ2dShHolr/2lGmYRPN74wmfQTzTkuQ/DBTILazagcnnUtarb43xGyVcYZi53TGebRYPJyPkaozWqeCIE2i9G4HeiBrCmEjwh2bprfBPvW10Av1PPNqobrS5Bf1iWUD+zOV5n45EgxsS//4lCwpK2+bVg8pez8mPwiYk7VWbqbNqfhpZd9XfMdIYogEMj2KX6fyVtDJlGIZD+twyvG30CbR8f4TXmVmzHZ4L26aNI=
after_success:
- bash <(curl -s https://codecov.io/bash)
